# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# the name of action
name: Upload Python Package mp-common-pkg

on:
  # When the master branch has a push, the action is triggered
  push: 
   branches:
     - master
  
  # When a PR is incorporated into the Master, an action is triggered
  # pull_request:
  #   branches:
  #     - master
  
  # Triggered when published action
  #release:
  #  types: [created]


jobs:
  deploy:
    name: publish python package to PYPI
    # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
    # This step USES GitHub https://github.com/actions/checkout
    - uses: actions/checkout@v2
    
    # set up the Python environment
    # This step USES GitHub https://github.com/actions/setup-python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    
    # Build and publish
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*